spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      topic: demo-topic
      properties:
        max:
          poll:
            interval:
              ms: 1000000
            records: 200
      group-id: reactive-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    in:
      vinodsharma: info